### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by PocketQuads** [uigormarshall/two-captcha#3]
Did you just code this without testing it even a single time?
the getId() method should return an id, instead it returns a string representation of an object with the key request, which includes the id.

Also, holy s***, you are supposed to put semicolons at the end of a line.

**Comment by uigormarshall** [comment]
Good night!
The tests were done and an issue was opened for this correction, in case this problem hinders you recommend that you make the correction and send a pull request, I will accept with happiness.
